name: Test, Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v7
      - name: setup node
        uses: actions/setup-node@v7
        with:
          node-version: 20
          cache: 'npm'
      - name: install packages
        run: npm ci
      - name: run unit tests
        run: npm test
      - name: build docker image
        run: |
          docker build -t website-retro .
          docker save website-retro -o website-retro-image.tar

      - name: upload docker image file
        uses: actions/upload-artifact@v7
        with:
          name: docker-image
          path: website-retro-image.tar

